services:
    db:
        image: mariadb:11
        environment:
            MYSQL_DATABASE: ${WORDPRESS_DB_NAME:-db}
            MYSQL_USER: ${WORDPRESS_DB_USER:-db}
            MYSQL_PASSWORD: ${WORDPRESS_DB_PASSWORD:-db}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
        volumes:
            - db_data:/var/lib/mysql
        networks:
            woo-ai-demo-network:

    adminer:
        image: adminer
        ports:
            - "${ADMINER_HOST_PORT:-8081}:8080"
        environment:
            ADMINER_DEFAULT_SERVER: ${WORDPRESS_DB_NAME:-db}
        networks:
            woo-ai-demo-network:

    wordpress:
        build: ./
        environment:
            WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME:-db}
            WORDPRESS_DB_USER: ${WORDPRESS_DB_USER:-db}
            WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD:-db}
            WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST:-db:3306}
            WORDPRESS_TABLE_PREFIX: ${WORDPRESS_TABLE_PREFIX:-sdg_}
            WORDPRESS_CONFIG_WP_HOME: ${WORDPRESS_CONFIG_WP_HOME:-${WORDPRESS_PROTOCOL:-http}://${WORDPRESS_DOMAIN:-localhost}:${WORDPRESS_HOST_PORT:-8080}}
            WORDPRESS_CONFIG_WP_SITEURL: ${WORDPRESS_CONFIG_WP_SITEURL:-${WORDPRESS_PROTOCOL:-http}://${WORDPRESS_DOMAIN:-localhost}:${WORDPRESS_HOST_PORT:-8080}}
            WORDPRESS_CONFIG_EXTRA: ${WORDPRESS_CONFIG_EXTRA:-define('WP_HOME',getenv_docker('WORDPRESS_CONFIG_WP_HOME','${WORDPRESS_PROTOCOL:-http}://${WORDPRESS_DOMAIN:-localhost}:${WORDPRESS_HOST_PORT:-8080}')); define('WP_SITEURL',getenv_docker('WORDPRESS_CONFIG_WP_SITEURL','${WORDPRESS_PROTOCOL:-http}://${WORDPRESS_DOMAIN:-localhost}:${WORDPRESS_HOST_PORT:-8080}')); define( 'FS_METHOD', 'direct'); define( 'DISABLE_WP_CRON', true ); define( 'WP_DEBUG_LOG', true); define( 'WP_DEBUG_DISPLAY', false);}
            WORDPRESS_DEBUG: ${WORDPRESS_DEBUG:-true}
        volumes:
            - ./:/var/www/
        ports:
            - "${WORDPRESS_HOST_PORT:-8080}:80"
        depends_on:
            - db
        networks:
            woo-ai-demo-network:

    wpcron:
        image: wordpress:cli
        environment:
            WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME:-db}
            WORDPRESS_DB_USER: ${WORDPRESS_DB_USER:-db}
            WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD:-db}
            WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST:-db:3306}
            WORDPRESS_TABLE_PREFIX: ${WORDPRESS_TABLE_PREFIX:-sdg_}
            WORDPRESS_CONFIG_WP_HOME: ${WORDPRESS_CONFIG_WP_HOME:-${WORDPRESS_PROTOCOL:-http}://${WORDPRESS_DOMAIN:-localhost}:${WORDPRESS_HOST_PORT:-8080}}
            WORDPRESS_CONFIG_WP_SITEURL: ${WORDPRESS_CONFIG_WP_SITEURL:-${WORDPRESS_PROTOCOL:-http}://${WORDPRESS_DOMAIN:-localhost}:${WORDPRESS_HOST_PORT:-8080}}
            WORDPRESS_CONFIG_EXTRA: ${WORDPRESS_CONFIG_EXTRA:-define('WP_HOME',getenv_docker('WORDPRESS_CONFIG_WP_HOME','${WORDPRESS_PROTOCOL:-http}://${WORDPRESS_DOMAIN:-localhost}:${WORDPRESS_HOST_PORT:-8080}')); define('WP_SITEURL',getenv_docker('WORDPRESS_CONFIG_WP_SITEURL','${WORDPRESS_PROTOCOL:-http}://${WORDPRESS_DOMAIN:-localhost}:${WORDPRESS_HOST_PORT:-8080}')); define( 'FS_METHOD', 'direct'); define( 'DISABLE_WP_CRON', true ); define( 'WP_DEBUG_LOG', true); define( 'WP_DEBUG_DISPLAY', false);}
            WORDPRESS_DEBUG: ${WORDPRESS_DEBUG:-true}
        volumes:
            - ./html:/var/www/html
        networks:
            woo-ai-demo-network:
        depends_on:
            - wordpress
        command: >
            /bin/bash -c " \
            set -x; \
            until wp db check --skip-ssl --path=/var/www/html; do \
            echo 'Waiting for database connection...' && sleep 5; \
            done; \
            while true; do \
            wp cron event run --due-now --path=/var/www/html 1>/dev/stdout 2>&1 || true; \
            sleep 900; \
            done;"

    weaviate:
        command:
            - --host
            - 0.0.0.0
            - --port
            - "${WEAVIATE_PORT:-8080}"
            - --scheme
            - ${WEAVIATE_PROTOCOL:-http}
        image: cr.weaviate.io/semitechnologies/weaviate:1.30.0
        ports:
            - 8082:${WEAVIATE_PORT:-8080}
            - 50051:50051
        volumes:
            - weaviate_data:/var/lib/weaviate
        restart: on-failure:0
        environment:
            CONTEXTIONARY_URL: contextionary:9999
            SPELLCHECK_INFERENCE_API: "http://text-spellcheck:8080"
            QUERY_DEFAULTS_LIMIT: 25
            AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: "true"
            PERSISTENCE_DATA_PATH: "/var/lib/weaviate"
            DEFAULT_VECTORIZER_MODULE: "text2vec-contextionary"
            ENABLE_MODULES: "text2vec-contextionary,text-spellcheck"
            CLUSTER_HOSTNAME: "node1"
        networks:
            woo-ai-demo-network:
    contextionary:
        environment:
            OCCURRENCE_WEIGHT_LINEAR_FACTOR: 0.75
            EXTENSIONS_STORAGE_MODE: weaviate
            EXTENSIONS_STORAGE_ORIGIN: ${WEAVIATE_PROTOCOL:-http}://${WEAVIATE_HOSTNAME:-weaviate}:${WEAVIATE_PORT:-8080}
            NEIGHBOR_OCCURRENCE_IGNORE_PERCENTILE: 5
            ENABLE_COMPOUND_SPLITTING: "false"
        image: cr.weaviate.io/semitechnologies/contextionary:en0.16.0-v1.2.1
        ports:
            - 9999:9999
        networks:
            woo-ai-demo-network:
    text-spellcheck:
        image: cr.weaviate.io/semitechnologies/text-spellcheck-model:pyspellchecker-en
        networks:
            woo-ai-demo-network:
    weaviate-ui:
        image: naaive/weaviate-ui:latest
        ports:
            - 8083:7777
        restart: unless-stopped
        depends_on:
            - weaviate
        environment:
            WEAVIATE_URL: "${WEAVIATE_PROTOCOL:-http}://${WEAVIATE_HOSTNAME:-weaviate}:${WEAVIATE_PORT:-8080}"
        networks:
            woo-ai-demo-network:

    wpcli:
        image: wordpress:cli
        environment:
            WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME:-db}
            WORDPRESS_DB_USER: ${WORDPRESS_DB_USER:-db}
            WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD:-db}
            WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST:-db:3306}
            WORDPRESS_TABLE_PREFIX: ${WORDPRESS_TABLE_PREFIX:-sdg_}
            WORDPRESS_CONFIG_WP_HOME: ${WORDPRESS_CONFIG_WP_HOME:-${WORDPRESS_PROTOCOL:-http}://${WORDPRESS_DOMAIN:-localhost}:${WORDPRESS_HOST_PORT:-8080}}
            WORDPRESS_CONFIG_WP_SITEURL: ${WORDPRESS_CONFIG_WP_SITEURL:-${WORDPRESS_PROTOCOL:-http}://${WORDPRESS_DOMAIN:-localhost}:${WORDPRESS_HOST_PORT:-8080}}
            WORDPRESS_CONFIG_EXTRA: ${WORDPRESS_CONFIG_EXTRA:-define('WP_HOME',getenv_docker('WORDPRESS_CONFIG_WP_HOME','${WORDPRESS_PROTOCOL:-http}://${WORDPRESS_DOMAIN:-localhost}:${WORDPRESS_HOST_PORT:-8080}')); define('WP_SITEURL',getenv_docker('WORDPRESS_CONFIG_WP_SITEURL','${WORDPRESS_PROTOCOL:-http}://${WORDPRESS_DOMAIN:-localhost}:${WORDPRESS_HOST_PORT:-8080}')); define( 'FS_METHOD', 'direct'); define( 'DISABLE_WP_CRON', true ); define( 'WP_DEBUG_LOG', true); define( 'WP_DEBUG_DISPLAY', false);}
            WORDPRESS_DEBUG: ${WORDPRESS_DEBUG:-true}
            WORDPRESS_PLUGINS_TO_ACTIVATE: ${WORDPRESS_PLUGINS_TO_ACTIVATE:-woocommerce wpsolr-free}
            WORDPRESS_ADMIN_USER: ${WORDPRESS_ADMIN_USER:-admin}
            WORDPRESS_ADMIN_PASSWORD: ${WORDPRESS_ADMIN_PASSWORD:-admin}
            WORDPRESS_ADMIN_EMAIL: ${WORDPRESS_ADMIN_EMAIL:-admin@example.com}
            WORDPRESS_SITE_TITLE: ${WORDPRESS_SITE_TITLE:-WordPress Site}
            WORDPRESS_DOMAIN: ${WORDPRESS_DOMAIN:-localhost}
            WORDPRESS_PROTOCOL: ${WORDPRESS_PROTOCOL:-http}
            WORDPRESS_HOST_PORT: ${WORDPRESS_HOST_PORT:-8080}
            WORDPRESS_CONFIG_WP_DEBUG: ${WORDPRESS_CONFIG_WP_DEBUG:-true}
        volumes:
            - ./html:/var/www/html
            - ./scripts:/scripts
        depends_on:
            - wordpress
        command: >
            /bin/bash /scripts/wpcli.sh
        networks:
            woo-ai-demo-network:

networks:
    woo-ai-demo-network:
        external: true

volumes:
    db_data:
    weaviate_data:
