all:
  vars:
    ansible_user: ansible
    build_number: "{{ ansible_date_time.iso8601_micro | to_uuid }}"
    required_docker_label: "org.andrewjdawes.application=andrewjdawes-woo-ai-demo"
    nginx_reverse_proxy_network_name: "nginx_proxy_network"
    MYSQL_ROOT_PASSWORD: "{{ lookup('env', 'MYSQL_ROOT_PASSWORD') }}"
    WORDPRESS_DB_NAME: "{{ lookup('env', 'WORDPRESS_DB_NAME') }}"
    WORDPRESS_DB_USER: "{{ lookup('env', 'WORDPRESS_DB_USER') }}"
    WORDPRESS_DB_PASSWORD: "{{ lookup('env', 'WORDPRESS_DB_PASSWORD') }}"
    WORDPRESS_CONFIG_ADMIN_PASSWORD: "{{ lookup('env', 'WORDPRESS_CONFIG_ADMIN_PASSWORD') }}"
    WORDPRESS_CONFIG_ADMIN_USER: "{{ lookup('env', 'WORDPRESS_CONFIG_ADMIN_USER') }}"
    WORDPRESS_CONFIG_ADMIN_EMAIL: "{{ lookup('env', 'WORDPRESS_CONFIG_ADMIN_EMAIL') }}"
    NEXTAPP_REVALIDATE_SECRET: "{{ lookup('env', 'NEXTAPP_REVALIDATE_SECRET') }}"
  hosts:
    # cdeed53d37a742f08a227faafc832595:
    #   ansible_host: 192.168.0.20
    # 9c9b38653dae4f4ebbd120adba40ac33:
    #   ansible_host: 192.168.0.28
    ad42e8b2fa7d4a3dbc5aecef7810a624:
      ansible_host: 192.168.0.21
      docker_networks:
        - name: "andrewjdawes_woo_ai_demo"
          driver: bridge
      docker_volumes:
        - name: "andrewjdawes_woo_ai_demo_db_data"
          driver: local
      docker_containers:
        - name: "andrewjdawes-woo-ai-demo-db"
          image: "mysql/mysql-server:8.0"
          state: "started"
          volumes:
            - "andrewjdawes_woo_ai_demo_db_data:/var/lib/mysql"
          networks:
            - name: "andrewjdawes_woo_ai_demo"
              aliases:
                - "db"
          env:
            MYSQL_DATABASE: "{{ WORDPRESS_DB_NAME }}"
            MYSQL_USER: "{{ WORDPRESS_DB_USER }}"
            MYSQL_PASSWORD: "{{ WORDPRESS_DB_PASSWORD }}"
            MYSQL_ROOT_PASSWORD: "{{ MYSQL_ROOT_PASSWORD }}"
          labels:
            org.andrewjdawes.application: "andrewjdawes-woo-ai-demo"
            org.andrewjdawes.service: "db"
            # org.andrewjdawes.build_number: "{{ build_number }}" # will force a recreate
          restart_policy: always
          replica_count: 1
          filters_string: '--filter "label=org.andrewjdawes.application=andrewjdawes-woo-ai-demo" --filter "label=org.andrewjdawes.service=db"'
          deploy_strategy: "recreate"
          comparisons:
            "*": ignore # by default, ignore *all* options (including image)
            image: strict
            networks: strict
            volumes: strict
            env: strict # except for environment variables; there, we want to be strict
            restart_policy: strict
            labels: strict # will force a recreate

        - name: "andrewjdawes-woo-ai-demo-phpmyadmin"
          image: "phpmyadmin/phpmyadmin"
          state: "started"
          depends_on:
            - "andrewjdawes-woo-ai-demo-db"
          networks:
            - name: "andrewjdawes_woo_ai_demo"
            - name: "{{ nginx_reverse_proxy_network_name }}"
              aliases:
                - phpmyadmin.andrewjdawes.net
          env:
            PMA_HOST: "db"
            PMA_PORT: "3306"
            PMA_USER: "{{ WORDPRESS_DB_USER }}"
            PMA_PASSWORD: "{{ WORDPRESS_DB_PASSWORD }}"
          labels:
            org.andrewjdawes.application: "andrewjdawes-woo-ai-demo"
            org.andrewjdawes.service: "phpmyadmin"
            # org.andrewjdawes.build_number: "{{ build_number }}"
          restart_policy: always
          replica_count: 1
          filters_string: '--filter "label=org.andrewjdawes.application=andrewjdawes-woo-ai-demo" --filter "label=org.andrewjdawes.service=phpmyadmin"'
          deploy_strategy: "recreate"

        - name: "andrewjdawes-woo-ai-demo-wp"
          image: "ghcr.io/andrewjdawes-github/andrewjdawes-website-wp:latest"
          pull: true
          state: "started"
          depends_on:
            - "andrewjdawes-woo-ai-demo-db"
          networks:
            - name: "andrewjdawes_woo_ai_demo"
            - name: "{{ nginx_reverse_proxy_network_name }}"
              aliases:
                - wp.andrewjdawes.net
          env:
            WORDPRESS_HOST_PORT: "80"
            WORDPRESS_DB_NAME: "{{ WORDPRESS_DB_NAME }}"
            WORDPRESS_DB_USER: "{{ WORDPRESS_DB_USER }}"
            WORDPRESS_DB_PASSWORD: "{{ WORDPRESS_DB_PASSWORD }}"
            WORDPRESS_DB_HOST: db:3306
            WORDPRESS_TABLE_PREFIX: sdg_
            WORDPRESS_HOST_NAME: wp.andrewjdawes.net
            WORDPRESS_CONFIG_WP_HOME: https://wp.andrewjdawes.net
            WORDPRESS_CONFIG_WP_SITEURL: https://wp.andrewjdawes.net
            WORDPRESS_CONFIG_EXTRA: define('WP_HOME',getenv_docker('WORDPRESS_CONFIG_WP_HOME','https://wp.andrewjdawes.net')); define('WP_SITEURL',getenv_docker('WORDPRESS_CONFIG_WP_SITEURL','https://wp.andrewjdawes.net')); define( 'FS_METHOD', 'direct'); define( 'DISABLE_WP_CRON', true ); define( 'WP_DEBUG_LOG', true); define( 'WP_DEBUG_DISPLAY', false);
            WORDPRESS_DEBUG: "true"
            NEXTAPP_BASE_API_URL: https://andrewjdawes.net/api
            NEXTAPP_REVALIDATE_SECRET: "{{ NEXTAPP_REVALIDATE_SECRET }}"
          labels:
            org.andrewjdawes.application: "andrewjdawes-woo-ai-demo"
            org.andrewjdawes.service: "wp"
            org.andrewjdawes.build_number: "{{ build_number }}"
          restart_policy: "always"
          replica_count: 2
          filters_string: '--filter "label=org.andrewjdawes.application=andrewjdawes-woo-ai-demo" --filter "label=org.andrewjdawes.service=wp"'
          deploy_strategy: "blue_green"
